### ISSUE TITLE
feat: sticky header

### ISSUE THREAD

**Issue by raulwwq0** [politecnicoDAW-2022/DIW-Proyecto-Gropy#6]
Since our original idea was to have a sticky nav, we need to implement it. However, our nav is inside the header in this new version, so we need to make a sticky header.

**Comment by Caballerog** [comment]
Recordadme que el próximo día en el proyecto, enseñe al resto de compañeros como trabajar con:

- issues de Github
- labels de Github
- milestones
- tableros Kanban.
- primer contacto con configuración de Github Actions (Git hooks) <- No profundizar porque puede que se imparta en HLC.

Vosotros seguid así.
